# $Id: Makefile,v 1.1 2003/08/01 11:47:36 nearora Exp $

CC = gcc
CFLAGS = -o -pthread -lpthread -ansi -pedantic -Wall
TARGETS = main

# rules

# default

# targets

all: $(TARGETS)

clean:
	rm -fr $(TARGETS) *~ *.o
